"""
Generate the raw-table DDL from the CSV header — pure codegen, no database.

WHY THIS EXISTS
    The raw table must have exactly the columns the file has — no more, no fewer,
    in the same order. Hand-writing a 150-column CREATE TABLE is how a blueprint
    silently drifts from the data (a typo, a missed column, a stale copy). So we
    don't hand-write it: we read the file's header and emit the DDL from it. The
    generated SQL is therefore provably faithful to the source by construction,
    and regenerating after any data refresh re-proves it.

THE DESIGN DECISIONS IT ENCODES
    - EVERY column is `text`. The load coerces nothing; typing is a later,
      documented staging decision. Text at load = zero silent data loss.
    - EVERY identifier is double-quoted. LendingClub ships reserved words as
      column names (notably `desc`); quoting makes them legal and also preserves
      exact case. We quote all, not just the reserved ones, for uniformity.
    - It FAILS LOUDLY on duplicate, blank, or over-63-byte column names. Postgres
      truncates identifiers to 63 bytes, so an over-long name could silently
      collide with another — exactly the kind of quiet corruption this project
      refuses. Better to stop and report than to generate a lie.

OUTPUT
    sql/01_create_raw.sql  (generated — do not hand-edit; re-run to refresh)
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

csv.field_size_limit(min(sys.maxsize, 2**31 - 1))

REPO = Path(__file__).resolve().parents[1]
RAW_DIR = REPO / "data" / "raw"
OUT = REPO / "sql" / "01_create_raw.sql"

TABLE = "public.loans_raw"
PG_IDENT_MAX_BYTES = 63


def find_raw_csv() -> Path:
    candidates = sorted(RAW_DIR.glob("*.csv"), key=lambda p: p.stat().st_size, reverse=True)
    if not candidates:
        sys.exit(f"No *.csv found in {RAW_DIR}")
    return candidates[0]


def read_header(path: Path) -> list[str]:
    """Read only the first record. utf-8-sig strips a BOM if present so the first
    column name is never prefixed with the BOM bytes."""
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return next(csv.reader(f))


def validate(header: list[str]) -> None:
    """Refuse to generate DDL from a header that would produce an ambiguous or
    illegal table. Every failure is fatal and named."""
    problems = []
    seen = {}
    for i, col in enumerate(header, 1):
        if col.strip() == "":
            problems.append(f"column {i}: blank name")
        if len(col.encode("utf-8")) > PG_IDENT_MAX_BYTES:
            problems.append(f"column {i}: name exceeds {PG_IDENT_MAX_BYTES} bytes -> `{col}`")
        if col in seen:
            problems.append(f"column {i}: duplicate of column {seen[col]} -> `{col}`")
        else:
            seen[col] = i
    if problems:
        sys.exit("Refusing to generate DDL:\n  - " + "\n  - ".join(problems))


def quote_ident(name: str) -> str:
    """Double-quote a Postgres identifier, escaping any embedded double-quote."""
    return '"' + name.replace('"', '""') + '"'


def build_ddl(header: list[str], source: Path) -> str:
    cols = ",\n".join(f"    {quote_ident(c)} text" for c in header)
    return (
        "-- GENERATED by scripts/01_generate_ddl.py — DO NOT EDIT.\n"
        "-- Regenerate from the source header instead of editing this file.\n"
        f"-- Source header: {source.name}\n"
        f"-- Columns: {len(header)} (every column loaded as text; typing is a staging decision)\n"
        "\n"
        f"CREATE TABLE {TABLE} (\n"
        f"{cols}\n"
        ");\n"
    )


def main() -> None:
    path = find_raw_csv()
    header = read_header(path)
    validate(header)
    ddl = build_ddl(header, path)
    OUT.write_text(ddl, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)}: {len(header)} columns as text from {path.name}")


if __name__ == "__main__":
    main()
